version: '3.8'

services:
  server:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - shared_volume:/shared
    command: ["npm", "run", "start"]

  client_web:
    build:
      context: ./frontend
    ports:
      - "8081:8081"
    volumes:
      - shared_volume:/shared
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  shared_volume:
